#include <tgbot/TgTypeParser.h>
#include <nlohmann/json.hpp>

namespace TgBot {

DECLARE_PARSER_FROM_JSON(Message) {
    auto result = std::make_shared<Message>();
    parse(data, "message_id", &result->messageId);
    parse(data, "message_thread_id", &result->messageThreadId);
    result->directMessagesTopic = parse<DirectMessagesTopic>(data, "direct_messages_topic");
    result->from = parse<User>(data, "from");
    result->senderChat = parse<Chat>(data, "sender_chat");
    parse(data, "sender_boost_count", &result->senderBoostCount);
    result->senderBusinessBot = parse<User>(data, "sender_business_bot");
    parse(data, "sender_tag", &result->senderTag);
    parse(data, "date", &result->date);
    parse(data, "business_connection_id", &result->businessConnectionId);
    result->chat = parseRequired<Chat>(data, "chat");
    result->forwardOrigin = parse<MessageOrigin>(data, "forward_origin");
    parse(data, "is_topic_message", &result->isTopicMessage);
    parse(data, "is_automatic_forward", &result->isAutomaticForward);
    result->replyToMessage = parse<Message>(data, "reply_to_message");
    result->externalReply = parse<ExternalReplyInfo>(data, "external_reply");
    result->quote = parse<TextQuote>(data, "quote");
    result->replyToStory = parse<Story>(data, "reply_to_story");
    parse(data, "reply_to_checklist_task_id", &result->replyToChecklistTaskId);
    result->viaBot = parse<User>(data, "via_bot");
    parse(data, "edit_date", &result->editDate);
    parse(data, "has_protected_content", &result->hasProtectedContent);
    parse(data, "is_from_offline", &result->isFromOffline);
    parse(data, "is_paid_post", &result->isPaidPost);
    parse(data, "media_group_id", &result->mediaGroupId);
    parse(data, "author_signature", &result->authorSignature);
    parse(data, "paid_star_count", &result->paidStarCount);
    parse(data, "text", &result->text);
    result->entities = parseArray<MessageEntity>(data, "entities");
    result->linkPreviewOptions = parse<LinkPreviewOptions>(data, "link_preview_options");
    result->suggestedPostInfo = parse<SuggestedPostInfo>(data, "suggested_post_info");
    parse(data, "effect_id", &result->effectId);
    result->animation = parse<Animation>(data, "animation");
    result->audio = parse<Audio>(data, "audio");
    result->document = parse<Document>(data, "document");
    result->paidMedia = parse<PaidMediaInfo>(data, "paid_media");
    result->photo = parseArray<PhotoSize>(data, "photo");
    result->sticker = parse<Sticker>(data, "sticker");
    result->story = parse<Story>(data, "story");
    result->video = parse<Video>(data, "video");
    result->videoNote = parse<VideoNote>(data, "video_note");
    result->voice = parse<Voice>(data, "voice");
    parse(data, "caption", &result->caption);
    result->captionEntities = parseArray<MessageEntity>(data, "caption_entities");
    parse(data, "show_caption_above_media", &result->showCaptionAboveMedia);
    parse(data, "has_media_spoiler", &result->hasMediaSpoiler);
    result->checklist = parse<Checklist>(data, "checklist");
    result->contact = parse<Contact>(data, "contact");
    result->dice = parse<Dice>(data, "dice");
    result->game = parse<Game>(data, "game");
    result->poll = parse<Poll>(data, "poll");
    result->venue = parse<Venue>(data, "venue");
    result->location = parse<Location>(data, "location");
    result->newChatMembers = parseArray<User>(data, "new_chat_members");
    result->leftChatMember = parse<User>(data, "left_chat_member");
    result->chatOwnerLeft = parse<ChatOwnerLeft>(data, "chat_owner_left");
    result->chatOwnerChanged = parse<ChatOwnerChanged>(data, "chat_owner_changed");
    parse(data, "new_chat_title", &result->newChatTitle);
    result->newChatPhoto = parseArray<PhotoSize>(data, "new_chat_photo");
    parse(data, "delete_chat_photo", &result->deleteChatPhoto);
    parse(data, "group_chat_created", &result->groupChatCreated);
    parse(data, "supergroup_chat_created", &result->supergroupChatCreated);
    parse(data, "channel_chat_created", &result->channelChatCreated);
    result->messageAutoDeleteTimerChanged = parse<MessageAutoDeleteTimerChanged>(data, "message_auto_delete_timer_changed");
    parse(data, "migrate_to_chat_id", &result->migrateToChatId);
    parse(data, "migrate_from_chat_id", &result->migrateFromChatId);
    result->pinnedMessage = parse(data["pinned_message"]);
    result->invoice = parse<Invoice>(data, "invoice");
    result->successfulPayment = parse<SuccessfulPayment>(data, "successful_payment");
    result->refundedPayment = parse<RefundedPayment>(data, "refunded_payment");
    result->usersShared = parse<UsersShared>(data, "users_shared");
    result->chatShared = parse<ChatShared>(data, "chat_shared");
    result->gift = parse<GiftInfo>(data, "gift");
    result->uniqueGift = parse<UniqueGiftInfo>(data, "unique_gift");
    result->giftUpgradeSent = parse<GiftInfo>(data, "gift_upgrade_sent");
    parse(data, "connected_website", &result->connectedWebsite);
    result->writeAccessAllowed = parse<WriteAccessAllowed>(data, "write_access_allowed");
    result->passportData = parse<PassportData>(data, "passport_data");
    result->proximityAlertTriggered = parse<ProximityAlertTriggered>(data, "proximity_alert_triggered");
    result->boostAdded = parse<ChatBoostAdded>(data, "boost_added");
    result->chatBackgroundSet = parse<ChatBackground>(data, "chat_background_set");
    result->checklistTasksDone = parse<ChecklistTasksDone>(data, "checklist_tasks_done");
    result->checklistTasksAdded = parse<ChecklistTasksAdded>(data, "checklist_tasks_added");
    result->directMessagePriceChanged = parse<DirectMessagePriceChanged>(data, "direct_message_price_changed");
    result->forumTopicCreated = parse<ForumTopicCreated>(data, "forum_topic_created");
    result->forumTopicEdited = parse<ForumTopicEdited>(data, "forum_topic_edited");
    result->forumTopicClosed = parse<ForumTopicClosed>(data, "forum_topic_closed");
    result->forumTopicReopened = parse<ForumTopicReopened>(data, "forum_topic_reopened");
    result->generalForumTopicHidden = parse<GeneralForumTopicHidden>(data, "general_forum_topic_hidden");
    result->generalForumTopicUnhidden = parse<GeneralForumTopicUnhidden>(data, "general_forum_topic_unhidden");
    result->giveawayCreated = parse<GiveawayCreated>(data, "giveaway_created");
    result->giveaway = parse<Giveaway>(data, "giveaway");
    result->giveawayWinners = parse<GiveawayWinners>(data, "giveaway_winners");
    result->giveawayCompleted = parse<GiveawayCompleted>(data, "giveaway_completed");
    result->paidMessagePriceChanged = parse<PaidMessagePriceChanged>(data, "paid_message_price_changed");
    result->suggestedPostApproved = parse<SuggestedPostApproved>(data, "suggested_post_approved");
    result->suggestedPostApprovalFailed = parse<SuggestedPostApprovalFailed>(data, "suggested_post_approval_failed");
    result->suggestedPostDeclined = parse<SuggestedPostDeclined>(data, "suggested_post_declined");
    result->suggestedPostPaid = parse<SuggestedPostPaid>(data, "suggested_post_paid");
    result->suggestedPostRefunded = parse<SuggestedPostRefunded>(data, "suggested_post_refunded");
    result->videoChatScheduled = parse<VideoChatScheduled>(data, "video_chat_scheduled");
    result->videoChatStarted = parse<VideoChatStarted>(data, "video_chat_started");
    result->videoChatEnded = parse<VideoChatEnded>(data, "video_chat_ended");
    result->videoChatParticipantsInvited = parse<VideoChatParticipantsInvited>(data, "video_chat_participants_invited");
    result->webAppData = parse<WebAppData>(data, "web_app_data");
    result->replyMarkup = parse<InlineKeyboardMarkup>(data, "reply_markup");
    return result;
}

DECLARE_PARSER_TO_JSON(Message) {
    JsonWrapper json;
    if (object) {
        json.put("message_id", object->messageId);
        json.put("message_thread_id", object->messageThreadId);
        json.put("direct_messages_topic", object->directMessagesTopic);
        json.put("from", object->from);
        json.put("sender_chat", object->senderChat);
        json.put("sender_boost_count", object->senderBoostCount);
        json.put("sender_business_bot", object->senderBusinessBot);
        json.put("sender_tag", object->senderTag);
        json.put("date", object->date);
        json.put("business_connection_id", object->businessConnectionId);
        json.put("chat", object->chat);
        json.put("forward_origin", object->forwardOrigin);
        json.put("is_topic_message", object->isTopicMessage);
        json.put("is_automatic_forward", object->isAutomaticForward);
        json.put("reply_to_message", object->replyToMessage);
        json.put("external_reply", object->externalReply);
        json.put("quote", object->quote);
        json.put("reply_to_story", object->replyToStory);
        json.put("reply_to_checklist_task_id", object->replyToChecklistTaskId);
        json.put("via_bot", object->viaBot);
        json.put("edit_date", object->editDate);
        json.put("has_protected_content", object->hasProtectedContent);
        json.put("is_from_offline", object->isFromOffline);
        json.put("is_paid_post", object->isPaidPost);
        json.put("media_group_id", object->mediaGroupId);
        json.put("author_signature", object->authorSignature);
        json.put("paid_star_count", object->paidStarCount);
        json.put("text", object->text);
        json.put("entities", object->entities);
        json.put("link_preview_options", object->linkPreviewOptions);
        json.put("suggested_post_info", object->suggestedPostInfo);
        json.put("effect_id", object->effectId);
        json.put("animation", object->animation);
        json.put("audio", object->audio);
        json.put("document", object->document);
        json.put("paid_media", object->paidMedia);
        json.put("photo", object->photo);
        json.put("sticker", object->sticker);
        json.put("story", object->story);
        json.put("video", object->video);
        json.put("video_note", object->videoNote);
        json.put("voice", object->voice);
        json.put("caption", object->caption);
        json.put("caption_entities", object->captionEntities);
        json.put("show_caption_above_media", object->showCaptionAboveMedia);
        json.put("has_media_spoiler", object->hasMediaSpoiler);
        json.put("checklist", object->checklist);
        json.put("contact", object->contact);
        json.put("dice", object->dice);
        json.put("game", object->game);
        json.put("poll", object->poll);
        json.put("venue", object->venue);
        json.put("location", object->location);
        json.put("new_chat_members", object->newChatMembers);
        json.put("left_chat_member", object->leftChatMember);
        json.put("chat_owner_left", object->chatOwnerLeft);
        json.put("chat_owner_changed", object->chatOwnerChanged);
        json.put("new_chat_title", object->newChatTitle);
        json.put("new_chat_photo", object->newChatPhoto);
        json.put("delete_chat_photo", object->deleteChatPhoto);
        json.put("group_chat_created", object->groupChatCreated);
        json.put("supergroup_chat_created", object->supergroupChatCreated);
        json.put("channel_chat_created", object->channelChatCreated);
        json.put("message_auto_delete_timer_changed", object->messageAutoDeleteTimerChanged);
        json.put("migrate_to_chat_id", object->migrateToChatId);
        json.put("migrate_from_chat_id", object->migrateFromChatId);
        json.put("pinned_message", object->pinnedMessage);
        json.put("invoice", object->invoice);
        json.put("successful_payment", object->successfulPayment);
        json.put("refunded_payment", object->refundedPayment);
        json.put("users_shared", object->usersShared);
        json.put("chat_shared", object->chatShared);
        json.put("gift", object->gift);
        json.put("unique_gift", object->uniqueGift);
        json.put("gift_upgrade_sent", object->giftUpgradeSent);
        json.put("connected_website", object->connectedWebsite);
        json.put("write_access_allowed", object->writeAccessAllowed);
        json.put("passport_data", object->passportData);
        json.put("proximity_alert_triggered", object->proximityAlertTriggered);
        json.put("boost_added", object->boostAdded);
        json.put("chat_background_set", object->chatBackgroundSet);
        json.put("checklist_tasks_done", object->checklistTasksDone);
        json.put("checklist_tasks_added", object->checklistTasksAdded);
        json.put("direct_message_price_changed", object->directMessagePriceChanged);
        json.put("forum_topic_created", object->forumTopicCreated);
        json.put("forum_topic_edited", object->forumTopicEdited);
        json.put("forum_topic_closed", object->forumTopicClosed);
        json.put("forum_topic_reopened", object->forumTopicReopened);
        json.put("general_forum_topic_hidden", object->generalForumTopicHidden);
        json.put("general_forum_topic_unhidden", object->generalForumTopicUnhidden);
        json.put("giveaway_created", object->giveawayCreated);
        json.put("giveaway", object->giveaway);
        json.put("giveaway_winners", object->giveawayWinners);
        json.put("giveaway_completed", object->giveawayCompleted);
        json.put("paid_message_price_changed", object->paidMessagePriceChanged);
        json.put("suggested_post_approved", object->suggestedPostApproved);
        json.put("suggested_post_approval_failed", object->suggestedPostApprovalFailed);
        json.put("suggested_post_declined", object->suggestedPostDeclined);
        json.put("suggested_post_paid", object->suggestedPostPaid);
        json.put("suggested_post_refunded", object->suggestedPostRefunded);
        json.put("video_chat_scheduled", object->videoChatScheduled);
        json.put("video_chat_started", object->videoChatStarted);
        json.put("video_chat_ended", object->videoChatEnded);
        json.put("video_chat_participants_invited", object->videoChatParticipantsInvited);
        json.put("web_app_data", object->webAppData);
        json.put("reply_markup", object->replyMarkup);
    }
    return json;
}

} // namespace TgBot
